export const transactions = [
  {
    id: 1,
    transactionType: "Deposit",
    amount: "+1,100.00",
    date: new Date("2024-03-21"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 2,
    transactionType: "Send on-chain",
    amount: "-600.00",
    date: new Date("2024-03-17"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 3,
    transactionType: "Deposit",
    amount: "+100",
    date: new Date("2024-03-16"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 4,
    transactionType: "Deposit",
    amount: "+100",
    date: new Date("2024-03-12"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 5,
    transactionType: "Withdraw",
    amount: "-2,100.00",
    date: new Date("2024-03-10"),
    type: "Bank Wire",
    status: "Complete",
  },
  {
    id: 6,
    transactionType: "Deposit",
    amount: "+100",
    date: new Date("2024-02-25"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 7,
    transactionType: "Deposit",
    amount: "+100",
    date: new Date("2024-01-21"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 8,
    transactionType: "Withdraw",
    amount: "-6,300.00",
    date: new Date("2024-01-15"),
    type: "Bank Wire",
    status: "Complete",
  },
  {
    id: 9,
    transactionType: "Deposit",
    amount: "+4,000.00",
    date: new Date("2024-01-13"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 10,
    transactionType: "Deposit",
    amount: "+100",
    date: new Date("2024-01-09"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 11,
    transactionType: "Deposit",
    amount: "+100",
    date: new Date("2024-01-04"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
];
